//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FishOrderDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FishOrderDetail()
        {
            this.CustomerPaymentDetails = new HashSet<CustomerPaymentDetail>();
        }
    
        public int sn { get; set; }
        public string shippingId { get; set; }
        public string customerId { get; set; }
        public string fishType { get; set; }
        public int quatity { get; set; }
        public decimal unitPrice { get; set; }
        public decimal totalAmount { get; set; }
        public decimal Balance { get; set; }
        public bool paidFull { get; set; }
        public string orderId { get; set; }
        public System.DateTime dateOrdered { get; set; }
    
        public virtual ArrivedBoatDetail ArrivedBoatDetail { get; set; }
        public virtual CustomerDetail CustomerDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerPaymentDetail> CustomerPaymentDetails { get; set; }
    }
}
