//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArrivedBoatDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArrivedBoatDetail()
        {
            this.FishOrderDetails = new HashSet<FishOrderDetail>();
        }
    
        public int sn { get; set; }
        public string shippingId { get; set; }
        public string CannoeType { get; set; }
        public string BoatNo { get; set; }
        public Nullable<int> QmainFish { get; set; }
        public Nullable<int> QlogoFish { get; set; }
        public Nullable<int> QbrokenFish { get; set; }
        public Nullable<int> totalQuantity { get; set; }
        public System.DateTime dateArrived { get; set; }
        public string leaderName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FishOrderDetail> FishOrderDetails { get; set; }
    }
}
