//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPaymentDetail
    {
        public int sn { get; set; }
        public string orderId { get; set; }
        public decimal Amount { get; set; }
        public string receiverName { get; set; }
        public System.DateTime dateReceived { get; set; }
        public string receiverSignature { get; set; }
    
        public virtual FishOrderDetail FishOrderDetail { get; set; }
    }
}
