//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomersWithDept
    {
        public string Name { get; set; }
        public string CannoeType { get; set; }
        public string BoatNo { get; set; }
        public string leaderName { get; set; }
        public string fishType { get; set; }
        public int quatity { get; set; }
        public decimal unitPrice { get; set; }
        public decimal totalAmount { get; set; }
        public decimal Balance { get; set; }
        public System.DateTime dateOrdered { get; set; }
        public System.DateTime dateArrived { get; set; }
    }
}
