//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPayment
    {
        public int customerPaymentId { get; set; }
        public int OrderId { get; set; }
        public decimal Amount { get; set; }
        public string ReceiverName { get; set; }
        public System.DateTime DateReceived { get; set; }
        public string ReceiverSignature { get; set; }
    
        public virtual FishOrder FishOrder { get; set; }
    }
}
