//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecretaryPaymentDetail
    {
        public int sn { get; set; }
        public string secretaryName { get; set; }
        public int DaysWorked { get; set; }
        public decimal Amount { get; set; }
        public string secretarySign { get; set; }
        public System.DateTime datePaid { get; set; }
    }
}
